version: '3.1'

services:
    wordpress:
        image: wordpress:4.9.8
        volumes:
            - ./target:/var/www/html
        environment:
            - WORDPRESS_DB_HOST=localhost:3306
            - WORDPRESS_DB_USER=robin
            - WORDPRESS_DB_PASSWORD=pucese
            - WORDPRESS_DB_NAME=wordpress
        ports:
            - 8085:80
